name: build

on:
  pull_request:
    branches:
      - '**'

jobs:
  windows-console-version:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: configure
        run: cmake ./console-version -B "./console-version/cmake-build-debug" -G "MinGW Makefiles"
      - name: build
        run: cmake --build ./console-version/cmake-build-debug/ --target all

  linux-console-version:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: configure
        run: cmake ./console-version -B "./console-version/cmake-build-debug" -G "Unix Makefiles"
      - name: build
        run: cmake --build ./console-version/cmake-build-debug/ --target all

  windows-SDL-version:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: prepare SDL2 library
        run: |
          mkdir ./SDL-version/SDL2-library
          Invoke-WebRequest https://www.libsdl.org/release/SDL2-devel-2.0.16-mingw.tar.gz -OutFile SDL-version/SDL2-Library/SDL2.tar.gz
          tar zxf .\SDL-version\SDL2-Library\SDL2.tar.gz -C .\SDL-version\SDL2-Library\
          rm .\SDL-version\SDL2-Library\SDL2.tar.gz
      - name: configure
        run: cmake ./SDL-version -B "./SDL-version/cmake-build-debug" -G "MinGW Makefiles"
      - name: build
        run: cmake --build ./SDL-version/cmake-build-debug/ --target all

  linux-SDL-version:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: prepare SDL2 library
        run: |
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get install libsdl2-dev
      - name: configure
        run: cmake ./SDL-version -B "./SDL-version/cmake-build-debug" -G "Unix Makefiles"
      - name: build
        run: cmake --build ./SDL-version/cmake-build-debug/ --target all