name: build

on:
  pull_request:
    branches:
      - '**'

jobs:
  windows-console-version:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: configure
        run: cmake ./console-version -B "./console-version/cmake-build-debug" -G "MinGW Makefiles"
      - name: build
        run: cmake --build ./console-version/cmake-build-debug/ --target all

  linux-console-version:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: configure
        run: cmake ./console-version -B "./console-version/cmake-build-debug" -G "Unix Makefiles"
      - name: build
        run: cmake --build ./console-version/cmake-build-debug/ --target all